/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: VIS-All-3D (https://sketchfab.com/VIS-All)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/placeholder-cube-green-10e6f365f6f64b29b868ee410377af62
Title: Placeholder-Cube Green
*/

import React,{useEffect} from 'react'
import { useGLTF, useAnimations} from '@react-three/drei'

export default function Model2(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/src/assets/the-s-model/scene.gltf')
  const { actions,names } = useAnimations(animations, group)
console.log(names);
useEffect(()=>{
actions[names[0]].reset().fadeIn().play();
},[])



  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube_cell013_cell023_0" position={[0.645, 1.712, 0.738]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell039_3" position={[-0.011, 0.231, 0.813]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell043_4" position={[-0.304, 0.012, 0.114]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell050_5" position={[-0.49, 0.994, 0.278]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell055_6" position={[-0.02, 0.922, -0.029]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell064_7" position={[-0.966, 0.896, -0.015]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell084_8" position={[-0.155, 1.01, -0.047]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell085_9" position={[-0.205, 1.008, 0.047]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell087_10" position={[-0.061, 0.959, -0.056]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell088_11" position={[-0.047, 0.987, -0.046]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell089_12" position={[-0.102, 1.001, -0.068]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell090_13" position={[-0.128, 0.999, -0.015]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell095_14" position={[-0.531, 0.249, -0.09]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell102_15" position={[-0.01, 1.568, 0.028]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell117_16" position={[-0.527, 1.501, -0.038]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell129_17" position={[-0.004, 1.458, 0.266]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell140_18" position={[-0.053, 1.454, 0.879]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell144_19" position={[0.005, 1.831, 0.249]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell145_20" position={[-0.068, 1.988, 0.937]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell146_21" position={[-0.902, 1.218, 0.021]}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell149_22" position={[-0.996, 1.092, -0.055]}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell150_23" position={[-0.967, 1.22, -0.053]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell152_24" position={[-0.992, 1.267, -0.057]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell158_25" position={[0.002, 1.899, 0.051]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell159_26" position={[0.005, 1.96, 0.023]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell160_27" position={[-0.961, 0.987, -0.413]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell161_28" position={[-0.897, 0.973, -0.229]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell163_29" position={[-0.952, 0.95, -0.436]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell165_30" position={[-0.644, 0.931, -0.482]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell196_31" position={[-0.526, 0.987, -0.149]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell206_32" position={[-0.57, 1.005, -0.563]}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell219_33" position={[-0.956, 0.032, -0.986]}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell220_34" position={[-0.311, 1.017, -0.206]}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell222_35" position={[-0.169, 0.992, -0.166]}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell224_36" position={[-0.411, 1.031, -0.385]}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell001_37" position={[0.784, 1.279, 0.705]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell002_38" position={[0.337, 1.68, -0.735]}>
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell003_39" position={[0.129, 1.697, -0.157]}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell004_40" position={[0.796, 1.698, -0.524]}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell005_41" position={[0.407, 1.169, -0.767]}>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell006_42" position={[0.054, 1.319, -0.731]}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell007_43" position={[0.141, 1.137, -0.165]}>
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell008_44" position={[0.491, 1.306, -0.353]}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell009_45" position={[0.011, 1.248, -0.343]}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell010_46" position={[0.859, 0.61, -0.166]}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell011_47" position={[0.102, 0.767, -0.392]}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell012_48" position={[0.272, 0.219, -0.204]}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell013_49" position={[0.331, 0.377, -0.726]}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell014_50" position={[0.537, 0.794, -0.258]}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell015_51" position={[0.649, 0.566, -0.771]}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell016_52" position={[0.611, 0.034, -0.299]}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell017_53" position={[0.897, 1.216, 0.197]}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell018_54" position={[0.219, 1.792, 0.49]}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell019_55" position={[0.265, 1.334, 0.77]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell020_56" position={[0.547, 1.273, 0.278]}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell021_57" position={[0.172, 1.236, 0.296]}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell022_58" position={[0.791, 1.674, 0.26]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell024_59" position={[0.529, 0.671, 0.252]}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell025_60" position={[0.756, 0.238, 0.573]}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell026_61" position={[0.381, 0.24, 0.253]}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell027_62" position={[0.731, 0.729, 0.68]}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell028_63" position={[0.321, 0.335, 0.743]}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell029_64" position={[0.221, 0.707, 0.694]}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell030_65" position={[0.881, 0.437, 0.164]}>
                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell031_66" position={[0.169, 0.777, 0.147]}>
                <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell032_67" position={[-0.303, 1.735, -0.38]}>
                <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell033_68" position={[-0.296, 1.74, -0.718]}>
                <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell034_69" position={[-0.313, 1.323, -0.705]}>
                <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell035_70" position={[-0.758, 1.402, -0.313]}>
                <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell036_71" position={[-0.298, 1.224, -0.322]}>
                <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell037_72" position={[-0.293, 0.201, 0.417]}>
                <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell038_73" position={[-0.077, 0.086, 0.468]}>
                <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell040_74" position={[-0.079, 0.271, 0.564]}>
                <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell041_75" position={[-0.161, 0.259, 0.055]}>
                <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell042_76" position={[-0.378, 0.121, 0.046]}>
                <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell044_77" position={[-0.26, 0.307, 0.245]}>
                <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell045_78" position={[-0.732, 0.907, 0.297]}>
                <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell046_79" position={[-0.846, 0.646, 0.242]}>
                <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell047_80" position={[-0.577, 0.555, 0.306]}>
                <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell048_81" position={[-0.878, 0.646, 0.592]}>
                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell049_82" position={[-0.57, 0.488, 0.494]}>
                <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell051_83" position={[-0.609, 0.844, 0.509]}>
                <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell052_84" position={[-0.453, 0.63, 0.775]}>
                <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell053_85" position={[-0.127, 0.626, 0.612]}>
                <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell054_86" position={[-0.046, 0.747, 0.181]}>
                <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell056_87" position={[-0.224, 0.928, 0.219]}>
                <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell057_88" position={[-0.026, 0.958, 0.225]}>
                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell058_89" position={[-0.251, 0.664, 0.338]}>
                <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell059_90" position={[-0.123, 0.871, 0.66]}>
                <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell060_91" position={[-0.688, 0.663, 0.1]}>
                <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell061_92" position={[-0.826, 0.881, -0.022]}>
                <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell062_93" position={[-0.665, 0.625, -0.037]}>
                <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell063_94" position={[-0.854, 0.627, -0.005]}>
                <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell065_95" position={[-0.858, 0.871, 0.104]}>
                <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell066_96" position={[-0.912, 0.625, 0.118]}>
                <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell067_97" position={[-0.653, 0.872, 0.023]}>
                <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell068_98" position={[-0.151, 0.581, -0.002]}>
                <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell069_99" position={[-0.423, 0.577, 0.188]}>
                <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell070_100" position={[-0.114, 0.945, -0.085]}>
                <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell071_101" position={[-0.318, 0.884, 0.035]}>
                <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell072_102" position={[-0.457, 0.628, 0.018]}>
                <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell073_103" position={[-0.492, 0.903, 0.111]}>
                <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell074_104" position={[-0.21, 0.881, -0.039]}>
                <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell075_105" position={[-0.085, 0.856, -0.078]}>
                <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell076_106" position={[-0.373, 0.463, 0.922]}>
                <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell077_107" position={[-0.574, 0.137, 0.701]}>
                <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell078_108" position={[-0.383, 0.056, 0.939]}>
                <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell079_109" position={[-0.177, 0.055, 0.788]}>
                <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell080_110" position={[-0.154, 0.262, 0.869]}>
                <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell081_111" position={[-0.417, 0.225, 0.793]}>
                <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell082_112" position={[-0.797, 0.283, 0.773]}>
                <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell083_113" position={[-0.063, 0.432, 0.942]}>
                <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell086_114" position={[-0.073, 0.977, -0.082]}>
                <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell091_115" position={[-0.651, 0.378, 0.175]}>
                <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell092_116" position={[-0.796, 0.13, 0.07]}>
                <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell093_117" position={[-0.651, 0.102, 0.277]}>
                <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell094_118" position={[-0.583, 0.29, 0.263]}>
                <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell096_119" position={[-0.911, 0.405, 0.086]}>
                <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell097_120" position={[-0.868, 0.229, 0.338]}>
                <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell098_121" position={[-0.586, 0.246, -0.025]}>
                <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell099_122" position={[-0.114, 1.585, 0.214]}>
                <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell100_123" position={[-0.122, 1.84, 0.014]}>
                <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell101_124" position={[-0.14, 1.593, 0.031]}>
                <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell103_125" position={[-0.428, 1.912, 0.15]}>
                <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell104_126" position={[-0.332, 1.712, 0.388]}>
                <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell105_127" position={[-0.374, 1.67, 0.121]}>
                <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell106_128" position={[-0.116, 1.76, 0.146]}>
                <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell107_129" position={[-0.769, 1.064, 0.089]}>
                <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell108_130" position={[-0.792, 1.174, 0.076]}>
                <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell109_131" position={[-0.67, 1.067, 0.809]}>
                <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell110_132" position={[-0.66, 1.147, 0.5]}>
                <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell111_133" position={[-0.875, 1.053, -0.077]}>
                <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell112_134" position={[-0.545, 1.081, 0.781]}>
                <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell113_135" position={[-0.59, 1.168, 0.06]}>
                <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell114_136" position={[-0.78, 1.819, 0.274]}>
                <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell115_137" position={[-0.624, 1.41, 0.108]}>
                <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell116_138" position={[-0.572, 1.523, 0.357]}>
                <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell118_139" position={[-0.813, 1.894, 0.021]}>
                <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell119_140" position={[-0.82, 1.416, 0.376]}>
                <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell120_141" position={[-0.861, 1.512, 0.095]}>
                <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell121_142" position={[-0.579, 1.627, 0.058]}>
                <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell122_143" position={[-0.254, 1.441, 0.38]}>
                <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell123_144" position={[-0.113, 1.296, 0.649]}>
                <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell124_145" position={[-0.329, 1.168, 0.091]}>
                <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell125_146" position={[-0.159, 1.341, 0.176]}>
                <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell126_147" position={[-0.35, 1.23, 0.492]}>
                <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell127_148" position={[-0.294, 1.111, 0.847]}>
                <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell128_149" position={[-0.271, 1.415, 0.617]}>
                <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell130_150" position={[-0.141, 1.571, 0.937]}>
                <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell131_151" position={[-0.397, 1.602, 0.765]}>
                <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell132_152" position={[-0.583, 1.847, 0.668]}>
                <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell133_153" position={[-0.754, 1.096, 0.905]}>
                <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell134_154" position={[-0.909, 1.853, 0.648]}>
                <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell135_155" position={[-0.378, 1.265, 0.899]}>
                <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell136_156" position={[-0.697, 1.384, 0.8]}>
                <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell137_157" position={[-0.254, 1.858, 0.88]}>
                <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell138_158" position={[-0.079, 1.598, 0.778]}>
                <mesh name="Object_318" geometry={nodes.Object_318.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell139_159" position={[-0.044, 1.595, 0.447]}>
                <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell141_160" position={[-0.038, 1.88, 0.913]}>
                <mesh name="Object_322" geometry={nodes.Object_322.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell142_161" position={[-0.114, 1.907, 0.854]}>
                <mesh name="Object_324" geometry={nodes.Object_324.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell143_162" position={[-0.053, 1.83, 0.628]}>
                <mesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell147_163" position={[-0.902, 1.166, 0.559]}>
                <mesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell148_164" position={[-0.94, 1.107, 0.106]}>
                <mesh name="Object_330" geometry={nodes.Object_330.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell151_165" position={[-0.927, 1.24, 0.163]}>
                <mesh name="Object_332" geometry={nodes.Object_332.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell153_166" position={[-0.207, 1.91, 0.594]}>
                <mesh name="Object_334" geometry={nodes.Object_334.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell154_167" position={[-0.183, 1.658, 0.511]}>
                <mesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell155_168" position={[-0.081, 1.759, 0.271]}>
                <mesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell156_169" position={[-0.072, 1.926, 0.2]}>
                <mesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell157_170" position={[-0.178, 1.811, 0.625]}>
                <mesh name="Object_342" geometry={nodes.Object_342.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell162_171" position={[-0.655, 0.977, -0.22]}>
                <mesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell164_172" position={[-0.622, 0.97, -0.409]}>
                <mesh name="Object_346" geometry={nodes.Object_346.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell166_173" position={[-0.81, 0.974, -0.41]}>
                <mesh name="Object_348" geometry={nodes.Object_348.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell167_174" position={[-0.236, 0.37, -0.894]}>
                <mesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell168_175" position={[-0.471, 0.139, -0.772]}>
                <mesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell169_176" position={[-0.251, 0.158, -0.84]}>
                <mesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell170_177" position={[-0.162, 0.358, -0.639]}>
                <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell171_178" position={[-0.734, 0.039, -0.945]}>
                <mesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell172_179" position={[-0.389, 0.412, -0.681]}>
                <mesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell173_180" position={[-0.673, 0.194, -0.897]}>
                <mesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell174_181" position={[-0.557, 0.365, -0.772]}>
                <mesh name="Object_364" geometry={nodes.Object_364.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell175_182" position={[-0.243, 0.416, -0.321]}>
                <mesh name="Object_366" geometry={nodes.Object_366.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell176_183" position={[-0.392, 0.375, -0.48]}>
                <mesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell177_184" position={[-0.43, 0.187, -0.254]}>
                <mesh name="Object_370" geometry={nodes.Object_370.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell178_185" position={[-0.2, 0.17, -0.461]}>
                <mesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell179_186" position={[-0.438, 0.127, -0.457]}>
                <mesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell180_187" position={[-0.529, 0.407, -0.385]}>
                <mesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell181_188" position={[-0.18, 0.139, -0.21]}>
                <mesh name="Object_378" geometry={nodes.Object_378.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell182_189" position={[-0.137, 0.666, -0.884]}>
                <mesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell183_190" position={[-0.406, 0.851, -0.763]}>
                <mesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell184_191" position={[-0.124, 0.852, -0.771]}>
                <mesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell185_192" position={[-0.251, 0.651, -0.67]}>
                <mesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell186_193" position={[-0.211, 0.878, -0.795]}>
                <mesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell187_194" position={[-0.385, 0.659, -0.833]}>
                <mesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell188_195" position={[-0.252, 0.876, -0.621]}>
                <mesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell189_196" position={[-0.212, 0.666, -0.517]}>
                <mesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell190_197" position={[-0.187, 0.888, -0.346]}>
                <mesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell191_198" position={[-0.205, 0.579, -0.295]}>
                <mesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell192_199" position={[-0.442, 0.606, -0.475]}>
                <mesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell193_200" position={[-0.446, 0.9, -0.472]}>
                <mesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell194_201" position={[-0.471, 0.962, -0.211]}>
                <mesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell195_202" position={[-0.415, 0.714, -0.224]}>
                <mesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell197_203" position={[-0.619, 0.635, -0.478]}>
                <mesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell198_204" position={[-0.771, 0.54, -0.214]}>
                <mesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell199_205" position={[-0.644, 0.529, -0.44]}>
                <mesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell200_206" position={[-0.882, 0.793, -0.201]}>
                <mesh name="Object_414" geometry={nodes.Object_414.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell201_207" position={[-0.679, 0.756, -0.245]}>
                <mesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell202_208" position={[-0.837, 0.801, -0.417]}>
                <mesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell203_209" position={[-0.889, 0.581, -0.406]}>
                <mesh name="Object_420" geometry={nodes.Object_420.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell204_210" position={[-0.657, 0.893, -0.307]}>
                <mesh name="Object_422" geometry={nodes.Object_422.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell205_211" position={[-0.73, 0.597, -0.768]}>
                <mesh name="Object_424" geometry={nodes.Object_424.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell207_212" position={[-0.925, 0.804, -0.713]}>
                <mesh name="Object_426" geometry={nodes.Object_426.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell208_213" position={[-0.798, 0.892, -0.744]}>
                <mesh name="Object_428" geometry={nodes.Object_428.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell209_214" position={[-0.609, 0.903, -0.771]}>
                <mesh name="Object_430" geometry={nodes.Object_430.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell210_215" position={[-0.601, 0.897, -0.596]}>
                <mesh name="Object_432" geometry={nodes.Object_432.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell211_216" position={[-0.861, 0.428, -0.885]}>
                <mesh name="Object_434" geometry={nodes.Object_434.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell212_217" position={[-0.916, 0.207, -0.801]}>
                <mesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell213_218" position={[-0.638, 0.224, -0.21]}>
                <mesh name="Object_438" geometry={nodes.Object_438.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell214_219" position={[-0.744, 0.107, -0.564]}>
                <mesh name="Object_440" geometry={nodes.Object_440.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell215_220" position={[-0.8, 0.314, -0.553]}>
                <mesh name="Object_442" geometry={nodes.Object_442.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell216_221" position={[-0.918, 0.113, -0.725]}>
                <mesh name="Object_444" geometry={nodes.Object_444.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell217_222" position={[-0.899, 0.266, -0.34]}>
                <mesh name="Object_446" geometry={nodes.Object_446.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell218_223" position={[-0.917, 0.124, -0.312]}>
                <mesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell221_224" position={[-0.696, 1.033, -0.163]}>
                <mesh name="Object_450" geometry={nodes.Object_450.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell223_225" position={[-0.545, 1.029, -0.445]}>
                <mesh name="Object_452" geometry={nodes.Object_452.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell225_226" position={[-0.666, 1.082, -0.344]}>
                <mesh name="Object_454" geometry={nodes.Object_454.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell226_227" position={[-0.574, 1.096, -0.432]}>
                <mesh name="Object_456" geometry={nodes.Object_456.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell227_228" position={[-0.557, 1.066, -0.23]}>
                <mesh name="Object_458" geometry={nodes.Object_458.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell228_229" position={[-0.795, 1.135, -0.852]}>
                <mesh name="Object_460" geometry={nodes.Object_460.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell229_230" position={[-0.673, 1.309, -0.631]}>
                <mesh name="Object_462" geometry={nodes.Object_462.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell230_231" position={[-0.894, 1.1, -0.58]}>
                <mesh name="Object_464" geometry={nodes.Object_464.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell231_232" position={[-0.656, 1.386, -0.891]}>
                <mesh name="Object_466" geometry={nodes.Object_466.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell232_233" position={[-0.874, 1.323, -0.653]}>
                <mesh name="Object_468" geometry={nodes.Object_468.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell233_234" position={[-0.922, 1.289, -0.765]}>
                <mesh name="Object_470" geometry={nodes.Object_470.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell234_235" position={[-0.713, 1.135, -0.605]}>
                <mesh name="Object_472" geometry={nodes.Object_472.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell235_236" position={[-0.892, 1.267, -0.879]}>
                <mesh name="Object_474" geometry={nodes.Object_474.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell236_237" position={[-0.664, 1.832, -0.902]}>
                <mesh name="Object_476" geometry={nodes.Object_476.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell237_238" position={[-0.646, 1.637, -0.654]}>
                <mesh name="Object_478" geometry={nodes.Object_478.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell238_239" position={[-0.677, 1.834, -0.641]}>
                <mesh name="Object_480" geometry={nodes.Object_480.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell239_240" position={[-0.887, 1.879, -0.603]}>
                <mesh name="Object_482" geometry={nodes.Object_482.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell240_241" position={[-0.839, 1.664, -0.881]}>
                <mesh name="Object_484" geometry={nodes.Object_484.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell241_242" position={[-0.891, 1.884, -0.813]}>
                <mesh name="Object_486" geometry={nodes.Object_486.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell242_243" position={[-0.886, 1.657, -0.666]}>
                <mesh name="Object_488" geometry={nodes.Object_488.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell243_244" position={[-0.606, 1.588, -0.9]}>
                <mesh name="Object_490" geometry={nodes.Object_490.geometry} material={materials['Material.001']} />
              </group>
              <group name="Plane001_245" position={[-0.206, -2.005, -0.027]} />
              <group name="Plane_1" position={[0.193, -0.017, 0]} scale={1.932}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_0} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/src/assets/the-s-model/scene.gltf')
